# Generated by Django 4.2.7 on 2024-02-23 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0012_image_remove_post_image_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/post_photos'),
        ),
    ]
