# Generated by Django 4.2.7 on 2024-02-26 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0015_tag_alter_post_options_comment_tags_post_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
