# Generated by Django 4.2.7 on 2024-02-26 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0016_remove_comment_tags_remove_post_tags_delete_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['created_on', 'shared_on']},
        ),
    ]
