# Generated by Django 4.2.7 on 2024-02-29 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0017_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_on', '-shared_on']},
        ),
    ]
